In [3]:
import numpy as np

In [9]:
a = np.array([[1,2,3],[1,2,3]], dtype="int16")
print(a)

[[1 2 3]
 [1 2 3]]


In [10]:
b = np.array([[1.2,2.3,3.9],[0.2,2.7,3.6]])
print(b)

[[1.2 2.3 3.9]
 [0.2 2.7 3.6]]


In [11]:
a.ndim

2

In [12]:
a.shape

(2, 3)

In [13]:
a.dtype

dtype('int16')

In [16]:
b.itemsize

8

In [17]:
a.size*a.itemsize

12

In [21]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)
a.shape

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

In [25]:
a[1,-2]

np.int64(13)

In [28]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
a[:, 0]

array([1, 8])

In [35]:
a[0, 1:6:2]

array([2, 4, 6])

In [39]:
a[1, -2] = 0
print(a)

a[0, :2] = [2, 1]
a

[[21 21 21 21  5  6  7]
 [ 8  9 10 11 12  0 14]]


array([[ 2,  1, 21, 21,  5,  6,  7],
       [ 8,  9, 10, 11, 12,  0, 14]])

In [44]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [46]:
np.ones((2,3), dtype="int8")

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [47]:
np.full((2,5),100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [62]:
np.random.seed(42)
np.random.rand(10)*50+50

array([68.72700594, 97.53571532, 86.59969709, 79.93292421, 57.80093202,
       57.79972602, 52.90418061, 93.30880729, 80.05575059, 85.40362889])

In [54]:
np.random.random_sample(a.shape)

array([[0.56352689, 0.26407104, 0.08085118, 0.52135912, 0.89883341,
        0.88421897, 0.93741999],
       [0.15605896, 0.00829699, 0.91149178, 0.04523525, 0.58514802,
        0.80700807, 0.69012923]])

In [73]:
np.random.randint(1,7, size=(4,2))

array([[4, 1],
       [6, 5],
       [5, 2],
       [5, 2]])

In [76]:
np.identity(5, dtype="int8")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [81]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [100]:
import math
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[math.floor(3/2), math.floor(3/2)] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [105]:
a = np.array([1,2,3])
b=a.copy()
b

array([1, 2, 3])

In [106]:
b[0] = 100
b

array([100,   2,   3])

In [107]:
a

array([1, 2, 3])

In [108]:
a+2

array([3, 4, 5])

In [109]:
a-2

array([-1,  0,  1])

In [110]:
a/2

array([0.5, 1. , 1.5])

In [111]:
a+b

array([101,   4,   6])

In [112]:
a**2

array([1, 4, 9])

In [116]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [119]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [126]:
result = np.matmul(a, b)
print(result)

[[6. 6.]
 [6. 6.]]


In [127]:
c = np.identity(3)
np.linalg.det(result)

np.float64(0.0)